# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:17:24+00:00

from __future__ import annotations

from enum import Enum


class Extension(Enum):
    atom = 'atom'
    rss = 'rss'
    html = 'html'
    json = 'json'
